---
name: "Build"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    strategy:
      matrix:
        java:
        - distribution: "zulu"
          version: "21"
        - distribution: "temurin"
          version: "21"
        - distribution: "adopt"
          version: "21"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Initialize CodeQL"
      uses: "github/codeql-action/init@v3"
      with:
        languages: "${{ matrix.language }}"
    - name: "Set up JDK ${{ matrix.java.version }}"
      uses: "actions/setup-java@v4"
      with:
        distribution: "${{ matrix.java.distribution }}"
        java-version: "${{ matrix.java.version }}"
        java-package: "jdk"
        cache: "maven"
    - name: "Set up Maven"
      uses: "stCarolas/setup-maven@v5"
      with:
        maven-version: "3.9.10"
    - run: "git fetch --prune --unshallow --tags"
    - run: "mvn -s settings.xml clean spotless:check install"
    - name: "Perform CodeQL Analysis"
      uses: "github/codeql-action/analyze@v3"
    - name: "Submit Dependency Snapshot"
      uses: "advanced-security/maven-dependency-submission-action@v5"
      with:
        token: "${{ secrets.GH_TOKEN }}"
        maven-args: "-s settings.xml"
